apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: legal-term-api
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: legal-term-api

